### ISSUE TITLE
Please Add A License To This Project

### ISSUE THREAD

**Issue by leohu1** [kmoroz/WanaKanaShaapu#3]
Please add a license to this project, so others can use it with out scruples.

**Comment by kmoroz** [comment]
Cheers! MIT Licence added.

**Comment by GoldenPotato137** [comment]
Hi Ksenia. Could you kindly consider adding license to the NuGet package metadata? The absence of the license on the NuGet listing might lead to issues with license compliance tools, which rely on this metadata to properly assess and report on the usage terms of the package.

According to [microsoft doc](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/nuget). A possible solution is to add `<PackageLicenseExpression>MIT</PackageLicenseExpression>` in `PropertyGroup` in `WanaKanaShaapu/WanaKanaShaapu.csproj`

**Comment by kmoroz** [comment]
Hi @GoldenPotato137 , thanks for reaching out. I've addressed the issue you've flagged. Let me know if there's anything else I can assist you with. Thanks for using my package.
