### ISSUE TITLE
An error occurs if the `CustomKanaMapping` key is uppercase.

### ISSUE THREAD

**Issue by little-method** [kmoroz/WanaKanaShaapu#5]
I do not want to convert `GG` to Kana.
So I set `CustomKanaMapping` as follows.

```cs
private string ToKana(string romaji)
{
    // var options = new DefaultOptions { CustomKanaMapping = new Dictionary<string, string> { { "gg", "gg" } } };   // OK
    var options = new DefaultOptions { CustomKanaMapping = new Dictionary<string, string> { { "GG", "GG" } } };   // NG
    var kana = WanaKana.ToKana(romaji, options);

    return $"{kana}({romaji})";
}
```

However, I get the following error

```
KeyNotFoundException: The given key 'G' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <f98723dd4586469db5213ec59da723ca>:0 
  at WanaKanaShaapu.Internal.Utils.ChangeNodeData (System.Collections.Generic.Dictionary`2[TKey,TValue] tree, System.String key, System. String value) 
```

Is there a solution to this error?

**Comment by kmoroz** [comment]
Hello @st-little ! Thanks for flagging the issue. I will look into it and come back to you as soon as I can. In the meantime, If you have other test cases for `CustomKanaMapping` don't hesitate to share them with me.

**Comment by little-method** [comment]
Hello @kmoroz .
I was able to solve this issue. Thank you very much for your investigation.

**Comment by kmoroz** [comment]
Hello @st-little ! 
I'm sorry I couldn't come back to you sooner. I've also fixed it, in case you wanted to have a look. Thanks for flagging it.
